# Generated by Django 3.0.7 on 2020-07-07 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circuitmap', '0005_add_new_status_codes'),
    ]

    operations = [
        migrations.AddField(
            model_name='synapseimport',
            name='n_expected_downstream_partners',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='synapseimport',
            name='n_expected_upstream_partners',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
